package com.ydh.yudemo.frame.database.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ydh.yudemo.frame.database.UserDb;

import com.ydh.yudemo.frame.database.db.UserDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDbDaoConfig;

    private final UserDbDao userDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDbDaoConfig = daoConfigMap.get(UserDbDao.class).clone();
        userDbDaoConfig.initIdentityScope(type);

        userDbDao = new UserDbDao(userDbDaoConfig, this);

        registerDao(UserDb.class, userDbDao);
    }
    
    public void clear() {
        userDbDaoConfig.clearIdentityScope();
    }

    public UserDbDao getUserDbDao() {
        return userDbDao;
    }

}
